### ISSUE TITLE
missing includes?

### ISSUE THREAD

**Issue by antithing** [ShudaLi/rgbd_pose_estimation#1]
Hi there, i am trying to run your library, but am seeing these missing files...
# include "Utility.hpp"
# include "AbsoluteOrientation.hpp"
# include "AbsoluteOrientationNormal.hpp"
# include "PnPPoseAdapter.hpp"
# include "AOPoseAdapter.hpp"
# include "NormalAOPoseAdapter.hpp"
# include "P3P.hpp"
# include "MinimalSolvers.hpp"
# include "Simulator.hpp"

I have linked boost and eigen, what am I missing here?

Thank you!

**Comment by ShudaLi** [comment]
Hi, thanks for your message. The main contents of this library will be available by the end of August.

**Comment by antithing** [comment]
ok great! Thanks again.
